name: GitHub-CodeScanning-Action

on:
  schedule:
    - cron: "25 0 * * *"
  push:
    branches:
      - main
    
jobs:
   Kenna-Action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Toolkit Repo
      uses: actions/checkout@v2
      with:
        repository: KennaSecurity/toolkit
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install --without development test
    - name: Run Toolkit
      run : exec bundle exec ruby toolkit.rb task=github_code_scanning github_token=${GH_TOKEN} kenna_connector_id=${KENNA_CONNECTOR_ID} github_username=${GH_USERNAME} kenna_api_host=${KENNA_API_HOST} kenna_api_key=${KENNA_API_KEY} github_repositories=${GH_REPOS}
      env:
        GH_TOKEN: "${{secrets.GH_TOKEN}}"
        GH_USERNAME: "${{secrets.GH_USERNAME}}"
        GH_REPOS: "${{secrets.GH_REPOS}}"
        KENNA_API_KEY: "${{secrets.KENNA_API_KEY}}"
        KENNA_CONNECTOR_ID: "${{secrets.KENNA_CONNECTOR_ID}}"
        KENNA_API_HOST:  "${{secrets.KENNA_API_HOST}}"